### ISSUE TITLE
Missed doc for the refarm_site location

### ISSUE THREAD

**Issue by olegush** [fidals/shopelectro#1007]
**Deploy process error**

**I try to deploy locally**

1. Cloned
```
git clone git@github.com:fidals/shopelectro.git
cd shopelectro/docker/
```

2. Created postgres and rabbit db. Set redis password. Generated Django secret keys. Fill env files **app** and **credentials**. 

3. Run 
`make deploy-dev`

3. Got the result:
```
$ make deploy-dev
make create-env
make[1]: Entering directory '/home/oleg/python/testtasks/shopelectro/docker'
Env file already exists. Remove it? [y/n]: y
Go to this files and fill them with your own values.
Files list: env_files/app,env_files/credentials,env_files/paths,env_files/ports.
Hope you finished to configure files from list below.
Now going to merge new config values to .env file. Let's do it? [y/n]: y
make[1]: Leaving directory '/home/oleg/python/testtasks/shopelectro/docker'
make create-config
make[1]: Entering directory '/home/oleg/python/testtasks/shopelectro/docker'
make[1]: Leaving directory '/home/oleg/python/testtasks/shopelectro/docker'
docker-compose pull
Pulling nodejs    ... done
Pulling postgres  ... done
Pulling rabbitmq  ... done
Pulling redis     ... done
Pulling app-drone ... done
Pulling app       ... done
Pulling selenium  ... done
Pulling lint      ... done
Pulling pdd       ... done
docker-compose up -d app
Recreating shopelectro_redis_1    ... done
Recreating shopelectro_rabbitmq_1 ... done
Recreating shopelectro_postgres_1 ... done
Recreating shopelectro_app_1      ... done
make build-static
make[1]: Entering directory '/home/oleg/python/testtasks/shopelectro/docker'
docker-compose run --rm nodejs gulp build
[08:31:46] Requiring external module babel-register

You've seen warning because of deprecated deps during npm install.
It's recursive deps of actual packages, that we are using.
So, it's nothing we can do.

internal/modules/cjs/loader.js:651
    throw err;
    ^

Error: Cannot find module '/usr/app/deps/ecommerce/front/paths.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at getAppSrcPaths (/usr/app/src/gulpfile.babel.js:39:10)
    at Object.<anonymous> (/usr/app/src/gulpfile.babel.js:59:24)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at loader (/usr/app/src/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/app/src/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:666:32)
Makefile:56: recipe for target 'build-static' failed
make[1]: *** [build-static] Error 1
make[1]: Leaving directory '/home/oleg/python/testtasks/shopelectro/docker'
Makefile:95: recipe for target 'deploy-dev' failed
make: *** [deploy-dev] Error 2
```

**Comment by duker33** [comment]
@olegush , it's well known issue of our dev machine deploy mech. To resolve it you need to do follow this steps:
1. clone refarm site repo: `cd ~/python/testtasks && git clone git@github.com:fidals/refarm-site.git`
2. Inside shopelectro repo fill `REFARM_DIR` env var with refarm-site dir: `REFARM_DIR=../../refarm-site`. The var lives in two env files: `shopelectro/docker/env_files/paths` and `shopelectro/docker/.env`
3. Run `make deploy` process again

**Comment by duker33** [comment]
@olegush , we should append README.md with instruction what to do with REFARM_SITE env to avoid such things in the future. Let's do it with this task. Assigned it to you.

Pull Request with README.md fix supposed to close the task

**Comment by duker33** [comment]
@olegush , you can refuse the task, of course

**Comment by olegush** [comment]
Done. thank you!
