### ISSUE TITLE
Remove config.py

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#265]
Connected with fidals/refarm-site#89

Снесём config.py. Переносим его содержимое в settings, utils и т.д.

MAIN_PAGE_TILE делаем отдельной сущностью в базе и прикручиваем к админке.

**Comment by duker33** [comment]
тут есть пара слов про админку, поэтому поставил 1h, не 30m

**Comment by Filarius** [comment]
Возможно я что-то упускаю, но у меня не получается настроить виртуалку убунты для запуска сайта.
Ставлю Docker и Docker Compose по инструкции с оф сайта докера.
После make dev (который без sudo сразу вываливается, один из шагов установки Docker без sudo не запускался) долгий процесс установки заканчивается строчками
`Pulling se-lint (fidals/coala-ci:latest)...
latest: Pulling from fidals/coala-ci
Digest: sha256:6ee227a5b08f6fea3bf6d2373b433c619e95bb9283c1a9b39bd38c20dcad4117
Status: Image is up to date for fidals/coala-ci:latest
make static
make[1]: Entering directory '/home/user/shopelectro/docker'
docker-compose run --rm se-nodejs bash -c "\
        npm install -g gulp-cli && \
        # we use `--no-optional` because some optional npm dependencies fail on install
/bin/sh: 3: Syntax error: Unterminated quoted string
Makefile:10: recipe for target 'static' failed
make[1]: *** [static] Error 2
make[1]: Leaving directory '/home/user/shopelectro/docker'
Makefile:19: recipe for target 'build' failed
make: *** [build] Error 2
`

**Comment by ivnglkv** [comment]
```
$ git diff docker/Makefile
diff --git a/docker/Makefile b/docker/Makefile
index a2485df..91287c7 100644
--- a/docker/Makefile
+++ b/docker/Makefile
@@ -9,7 +9,6 @@ migrate:
 static:
        $(dc) run --rm se-nodejs bash -c "\
                npm install -g gulp-cli && \
-               # we use `--no-optional` because some optional npm dependencies fail on install
                npm install --no-optional && \
                gulp build"
 ```

Еще нужно будет сделать так. Не знаю, насколько это правильное было решение, но у меня вроде сработало

```
$ git diff docker/docker-compose.yml
diff --git a/docker/docker-compose.yml b/docker/docker-compose.yml
index 22c4cc6..7d7f630 100644
--- a/docker/docker-compose.yml
+++ b/docker/docker-compose.yml
@@ -66,6 +66,8 @@ services:
     volumes_from:
       - se-source
       - se-python
+    volumes:
+      - $REFARM_SRC:$DEPS_DIR
     environment:
       - DEPS_DIR=$DEPS_DIR
```

**Comment by artemiy312** [comment]
@Filarius 
>Docker без sudo не запускался

https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user

**Comment by Filarius** [comment]
после всесения данных изменений
make dev
выдал ошибку что нужно доустановить babeljs вручную
повторый запуск
make dev
выдал следующее

> user@ubuntu:~/shopelectro/docker$ make dev

> docker-compose build --no-cache se-python  # fetch <DEPS>/refarm-site/front/ dirdocker-compose build --no-cache se-python
> Building se-python
> Traceback (most recent call last):
>   File "bin/docker-compose", line 6, in <module>
>   File "compose/cli/main.py", line 71, in main
>   File "compose/cli/main.py", line 124, in perform_command
>   File "compose/cli/main.py", line 254, in build
>   File "compose/project.py", line 372, in build
>   File "compose/service.py", line 989, in build
>   File "site-packages/docker/api/build.py", line 150, in build
>   File "site-packages/docker/utils/build.py", line 14, in tar
>   File "site-packages/docker/utils/utils.py", line 103, in create_archive
> IOError: Can not access file in context: /home/user/shopelectro/node_modules/.bin/bin-version-check
> Failed to execute script docker-compose
C sudo анологично

Попробую очередной заход установки, но может есть инструкция которая вот точно будет работать, и, как говорится - For Dummies?
> Makefile:18: recipe for target 'build' failed
> make: *** [build] Error 255
Наверное нужно

**Comment by ivnglkv** [comment]
Странно. На babel выдает предупреждение то ли `npm install`, то ли `gulp build`, не помню точно. Что-то типа `babel package is required`. Но это именно предупреждение, не ошибка. После этого идет билд статики и если refam-site скачан и путь до него верно указан в переменной `REFARM-SRC` в `.env`, всё должно быть нормально.

Пробовал удалять контейнеры и тома из докера перед `make dev`?

А, всё, понял где сейчас ошибка. Что-то не то с локальной установкой ноды, или python. Там по идее ничего трогать не надо было, все манипуляции происходят внутри контейнеров

**Comment by duker33** [comment]
> но может есть инструкция которая вот точно будет работать

@Filarius , тут дело не в инструкции, а в стабильности сборки. Я и сам бывает с ним помучаюсь.
У нас есть нес-ко тасков по упрощению npm'а (#248 например), это должно увеличить стабильность

**Comment by Filarius** [comment]
@ivnglkv 

> P.S.
> А можешь показать Makefile и docker-compose.yml?

Приложил. Собственно изменил только те строки что ты указал.

[1.zip](https://github.com/fidals/shopelectro/files/1803091/1.zip)

**Comment by Filarius** [comment]
@ivnglkv 

> P.S.
> А можешь показать Makefile и docker-compose.yml?

Приложил. Собственно изменил только те строки что ты указал.

[1.zip](https://github.com/fidals/shopelectro/files/1803091/1.zip)

**Comment by duker33** [comment]
@Filarius , лучше запуши изменения в отдельную ветку. Так можно будет посмотреть дифф.
Код из zip-архива не очень удобно ревьювить

**Comment by Filarius** [comment]
[Makefile.txt](https://github.com/fidals/shopelectro/files/1803355/Makefile.txt)
[docker-compose.yml..txt](https://github.com/fidals/shopelectro/files/1803356/docker-compose.yml.txt)

**Comment by Filarius** [comment]
@duker33 и как будет удобней?
Самым быстрым способом для меня считается просто приложить файл к комментарию, но гитхаб разрешает это только для определенного типа файлов. Кинуть два перемененных txt будет аналогичным решением

**Comment by duker33** [comment]
@Filarius , коммитишь текущий код, создаёшь новую ветку типа `265_check_docker_config` и пушишь в репу.

Ветка появляется здесь, в репе вместе с твоими коммитами. Мы смотрим на нес-ко строк диффа вместо архива с кодом

**Comment by duker33** [comment]
зависит от CI

**Comment by duker33** [comment]
CI repaired
