### ISSUE TITLE
Fix CI test pipeline

### ISSUE THREAD

**Issue by artemiy312** [fidals/shopelectro#326]
```bash
python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/drone/src/github.com/fidals/shopelectro/pull/325/shopelectro/settings/dev.py", line 1, in <module>
    from .base import *
  File "/drone/src/github.com/fidals/shopelectro/pull/325/shopelectro/settings/base.py", line 353, in <module>
    PRICE_MULTIPLIERS = [float(p) for p in os.getenv('PRICE_MULTIPLIERS').split(', ')]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by artemiy312** [comment]
Seems, the error occurs because branch is stale and requires an update
