### ISSUE TITLE
Mail worker broken

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#424]
PO says that mail doesn't work on prod.

`dcp logs celery-mail-worker` run on prod returns traceback:

```
...
se-celery-mail-worker    | Traceback (most recent call last):
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/kombu/transport/base.py", line 123, in __getattr__
se-celery-mail-worker    |     return self[key]
se-celery-mail-worker    | KeyError: 'async'
se-celery-mail-worker    |
se-celery-mail-worker    | During handling of the above exception, another exception occurred:
se-celery-mail-worker    |
se-celery-mail-worker    | Traceback (most recent call last):
se-celery-mail-worker    |   File "/usr/local/bin/celery", line 11, in <module>
se-celery-mail-worker    |     sys.exit(main())
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 14, in main
se-celery-mail-worker    |     _main()
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 326, in main
se-celery-mail-worker    |     cmd.execute_from_commandline(argv)
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
se-celery-mail-worker    |     super(CeleryCommand, self).execute_from_commandline(argv)))
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
se-celery-mail-worker    |     return self.handle_argv(self.prog_name, argv[1:])
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 480, in handle_argv
se-celery-mail-worker    |     return self.execute(command, argv)
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 412, in execute
se-celery-mail-worker    |     ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/worker.py", line 221, in run_from_argv
se-celery-mail-worker    |     return self(*args, **options)
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 244, in __call__
se-celery-mail-worker    |     ret = self.run(*args, **kwargs)
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/worker.py", line 255, in run
se-celery-mail-worker    |     **kwargs)
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/worker/worker.py", line 99, in __init__
se-celery-mail-worker    |     self.setup_instance(**self.prepare_args(**kwargs))
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/worker/worker.py", line 122, in setup_instance
se-celery-mail-worker    |     self.should_use_eventloop() if use_eventloop is None
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/worker/worker.py", line 241, in should_use_eventloop
se-celery-mail-worker    |     self._conninfo.transport.implements.async and
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/kombu/transport/base.py", line 125, in __getattr__
se-celery-mail-worker    |     raise AttributeError(key)
se-celery-mail-worker    | AttributeError: async
root@web:~/prog/shopelectro/docker# dcp logs celery-mail-worker | tail -n 70
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
se-celery-mail-worker    |     super(CeleryCommand, self).execute_from_commandline(argv)))
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
se-celery-mail-worker    |     return self.handle_argv(self.prog_name, argv[1:])
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 480, in handle_argv
se-celery-mail-worker    |     return self.execute(command, argv)
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 412, in execute
se-celery-mail-worker    |     ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/worker.py", line 221, in run_from_argv
se-celery-mail-worker    |     return self(*args, **options)
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 244, in __call__
se-celery-mail-worker    |     ret = self.run(*args, **kwargs)
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/worker.py", line 255, in run
se-celery-mail-worker    |     **kwargs)
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/worker/worker.py", line 99, in __init__
se-celery-mail-worker    |     self.setup_instance(**self.prepare_args(**kwargs))
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/worker/worker.py", line 122, in setup_instance
se-celery-mail-worker    |     self.should_use_eventloop() if use_eventloop is None
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/celery/worker/worker.py", line 241, in should_use_eventloop
se-celery-mail-worker    |     self._conninfo.transport.implements.async and
se-celery-mail-worker    |   File "/usr/local/lib/python3.6/site-packages/kombu/transport/base.py", line 125, in __getattr__
se-celery-mail-worker    |     raise AttributeError(key)
se-celery-mail-worker    | AttributeError: async
```

**Comment by duker33** [comment]
seems it's version conflict: our celery uses too new version of kombu.

`4.2.1` kombu's version uses new Transport class's field names
https://github.com/celery/kombu/blob/master/kombu/transport/base.py#L135

**Comment by duker33** [comment]
... and celery don't control versions during build
https://github.com/celery/celery/blob/master/setup.cfg#L21

**Comment by duker33** [comment]
celery released hotfix according to this issue.
http://www.celeryproject.org/news/celery-411-hot-fix-releaesd/

I'll try to reniew it for 4.2.0 version

**Comment by duker33** [comment]
fixed on prod

`2h` includes chat with PO, working with prod
