### ISSUE TITLE
tests_commands.py:100: Resurrect delete prods test

### ISSUE THREAD

**Issue by 0pdd** [fidals/shopelectro#460]
The puzzle `452-ce38bf44` from #452 has to be resolved:

https://github.com/fidals/shopelectro/blob/5a1b98449c33eece3fe12dcc96b33caafd04657f/shopelectro/tests/tests_commands.py#L100-L100

The puzzle was created by duker33 on 28-Jul-18. 

Estimate: 15 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@artemiyds2 @duker33 please pay attention to this new issue.

**Comment by olegush** [comment]
```
======================================================================
ERROR: setUpClass (shopelectro.tests.tests_commands.UpdateProducts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/test/testcases.py", line 1042, in setUpClass
    cls.setUpTestData()
  File "/usr/app/src/shopelectro/tests/tests_commands.py", line 141, in setUpTestData
    call_command('update_catalog', '--recipients', 'username@example.com')
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/app/src/shopelectro/management/commands/update_catalog.py", line 25, in handle
    self.update(*args, **kwargs)
  File "/usr/app/src/shopelectro/management/commands/update_catalog.py", line 29, in update
    with utils.download_catalog(destination=settings.ASSETS_DIR):
  File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/app/src/shopelectro/management/commands/_update_catalog/utils.py", line 121, in download_catalog
    destination, settings.FTP_IP)), 'Files do not downloaded...'
AssertionError: Files do not downloaded...
```

@duker33 , I suppose I need FTP-access

**Comment by duker33** [comment]
i've given access to Oleg with with a direct message
