### ISSUE TITLE
Fix product page

### ISSUE THREAD

**Issue by artemiy312** [fidals/shopelectro#562]
**Description**
Get 500 error from product page

**To Reproduce**
1. Go to https://www.shopelectro.ru/catalog/products/276/

**Screenshots**

<img width="705" alt="default" src="https://user-images.githubusercontent.com/13870342/45000079-94d45c80-afca-11e8-8fc9-bd1800332691.png">

**Additional context**
traceback:
```python
se-python                | Internal Server Error: /catalog/products/276/
se-python                | Traceback (most recent call last):
se-python                |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 39, in inner
se-python                |     response = get_response(request)
se-python                |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
se-python                |     response = self.process_exception_by_middleware(e, request)
se-python                |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
se-python                |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
se-python                |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
se-python                |     return self.dispatch(request, *args, **kwargs)
se-python                |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
se-python                |     return bound_func(*args, **kwargs)
se-python                |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
se-python                |     response = view_func(request, *args, **kwargs)
se-python                |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
se-python                |     return func.__get__(self, type(self))(*args2, **kwargs2)
se-python                |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
se-python                |     return handler(request, *args, **kwargs)
se-python                |   File "/usr/app/src/shopelectro/views/catalog.py", line 112, in get
se-python                |     self.object = self.get_object()
se-python                |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/detail.py", line 53, in get_object
se-python                |     obj = queryset.get()
se-python                |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 389, in get
se-python                |     (self.model._meta.object_name, num)
se-python                | shopelectro.models.MultipleObjectsReturned: get() returned more than one Product -- it returned 6!
```

**Comment by artemiy312** [comment]
I did not find any problems with the code, so it seems this issue only about corrupted data. I am going to create a migration for duplicated products.

**Comment by duker33** [comment]
@artemiy312 , you can check if data is duplicated with `python shell` on prod serv.
If it's true, prod serv contains such data, we should add some checks to price generation
