### ISSUE TITLE
Create tests for order

### ISSUE THREAD

**Issue by duker33** [fidals/shopelectro#619]
Create tests for order. Right now we have failed order mech on prod because of no order tests.

```
| Internal Server Error: /shop/order/
| Traceback (most recent call last):
|File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
|  return self.cursor.execute(sql, params)
| psycopg2.IntegrityError: null value in column "revenue" violates not-null constraint
| DETAIL:  Failing row contains (8696, cash, , , null).
|
|
| The above exception was the direct cause of the following exception:
|
| Traceback (most recent call last):
|File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 39, in inner
|  response = get_response(request)
|File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
|  response = self.process_exception_by_middleware(e, request)
|File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
|  response = wrapped_callback(request, *callback_args, **callback_kwargs)
|File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
|  return self.dispatch(request, *args, **kwargs)
|File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
|  return handler(request, *args, **kwargs)
|File "/usr/local/lib/python3.6/site-packages/ecommerce/views.py", line 83, in post
|  order = save_order(form, cart)
|File "/usr/local/lib/python3.6/site-packages/ecommerce/views.py", line 65, in save_order
|  order_ = form_.save()
|File "/usr/local/lib/python3.6/site-packages/django/forms/models.py", line 448, in save
|  self.instance.save()
|File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 796, in save
|  force_update=force_update, update_fields=update_fields)
|File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 824, in save_base
|  updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
|File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 908, in _save_table
|  result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
|File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 947, in _do_insert
|  using=using, raw=raw)
|File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
|  return getattr(self.get_queryset(), name)(*args, **kwargs)
|File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1043, in _insert
|  return query.get_compiler(using=using).execute_sql(return_id)
|File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
|  cursor.execute(sql, params)
|File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
|  return self.cursor.execute(sql, params)
|File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
|  six.reraise(dj_exc_type, dj_exc_value, traceback)
|File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
|  raise value.with_traceback(tb)
|File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
|  return self.cursor.execute(sql, params)
| django.db.utils.IntegrityError: null value in column "revenue" violates not-null constraint
| DETAIL:  Failing row contains (8696, cash, , , null).
```

**Comment by artemiy312** [comment]
@duker33 We should test the ability to perform orders at SE side, because revenue calculates only for SE and RF tests won't catch the above issue

**Comment by artemiy312** [comment]
By the way, we already have such kind of tests in  `se.tests.selenium_tests.OrderPage` and they didn't help us to catch the issue. It is strange.

**Comment by duker33** [comment]
hmm, it's true. But now we'll wait until next time =)
