### ISSUE TITLE
Missed TEMPLATE_DEBUG in settings

### ISSUE THREAD

**Issue by artemiy312** [fidals/shopelectro#680]
se-python                | Traceback (most recent call last):
se-python                |   File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 208, in render
se-python                |     return template.render(context.new(values))
se-python                |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 210, in render
se-python                |     return self._render(context)
se-python                |   File "/usr/local/lib/python3.7/site-packages/django/test/utils.py", line 94, in instrumented_test_render
se-python                |     return self.nodelist.render(context)
se-python                |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 994, in render
se-python                |     bit = node.render_annotated(context)
se-python                |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 961, in render_annotated
se-python                |     return self.render(context)
se-python                |   File "/usr/local/lib/python3.7/site-packages/django/template/defaulttags.py", line 323, in render
se-python                |     return nodelist.render(context)
se-python                |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 994, in render
se-python                |     bit = node.render_annotated(context)
se-python                |   File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 961, in render_annotated
se-python                |     return self.render(context)
se-python                |   File "/usr/local/lib/python3.7/site-packages/sorl/thumbnail/templatetags/thumbnail.py", line 66, in render
se-python                |     if settings.TEMPLATE_DEBUG:
se-python                |   File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
se-python                |     return getattr(self._wrapped, name)
se-python                | AttributeError: 'Settings' object has no attribute 'TEMPLATE_DEBUG'

**Comment by artemiy312** [comment]
I have set it to `False` in `local.py` at prod
